compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_hostfile: /etc/mpi/hostfile # hostfile的路径
  #deepspeed_multinode_launcher: MPI  # 使用pdsh
  deepspeed_config_file: /ytech_m2v8_hdd/workspace/kling_mm/libozhou/feature_combination/zero2.json
distributed_type: DEEPSPEED
dynamo_config: {}
fsdp_config: {}
megatron_lm_config: {}
machine_rank: 0
#main_process_ip: '10.252.128.132' # 主机地址
main_process_port: 29500 # 端口
main_training_function: main
num_machines: 8 # GPU集群中node节点数
num_processes: 64  # 总的gpu的数量
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false